name: "neuro_sleep"
version: "1.0.0"
config-version: 2

profile: "neuro_sleep"

model-paths:
  - "models"

test-paths:
  - "tests"

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  silver_schema_version: "1.0.0"
  subject_metadata_transform_version: "1.0.0"
  recording_transform_version: "1.1.0"
