insert into governance.column_classification (
    table_schema,
    table_name,
    column_name,
    data_layer,
    classification_level,
    contains_personal_data,
    contains_health_data,
    contains_direct_identifier,
    sensitivity_reason,
    access_policy,
    masking_policy
)
select
    'warehouse',
    table_name,
    column_name,
    'warehouse',
    classification_level,
    contains_personal_data,
    contains_health_data,
    false,
    sensitivity_reason,
    access_policy,
    masking_policy
from (
    values
        ('dim_subject', 'subject_sk', 'confidential', true, true, 'Pseudonymous Warehouse subject identity linked to health data.', 'restricted', 'none'),
        ('dim_subject', 'subject_key', 'confidential', true, true, 'Deterministic pseudonymous logical subject key linked to health data.', 'restricted', 'none'),
        ('dim_subject', 'source_system', 'internal', false, false, 'External source-system identifier.', 'team_only', 'none'),
        ('dim_subject', 'dataset_version', 'internal', false, false, 'Source dataset version.', 'team_only', 'none'),
        ('dim_subject', 'collection', 'confidential', false, true, 'Subject-level Sleep-EDF collection membership.', 'restricted', 'none'),
        ('dim_subject', 'age_years', 'confidential', true, true, 'Exact subject age used in health-data analysis.', 'restricted', 'aggregate_only'),
        ('dim_subject', 'sex', 'confidential', true, true, 'Subject demographic attribute linked to health data.', 'restricted', 'aggregate_only'),
        ('dim_subject', 'source_subject_id', 'restricted', true, true, 'Source participant identifier from a finite public health dataset.', 'restricted', 'redact'),
        ('dim_subject', 'source_subject_number', 'restricted', true, true, 'Source participant number that can be combined with other quasi-identifiers.', 'restricted', 'redact'),
        ('dim_subject', 'source_bucket', 'internal', false, false, 'Bronze object-storage bucket retained for lineage.', 'team_only', 'none'),
        ('dim_subject', 'source_object_key', 'restricted', true, true, 'Lineage path to the source subject workbook.', 'restricted', 'redact'),
        ('dim_subject', 'metadata_input_fingerprint', 'confidential', false, true, 'Content identity of the selected subject-metadata publication.', 'restricted', 'none'),
        ('dim_subject', 'first_loaded_at', 'internal', false, false, 'Earliest accepted staging lineage timestamp for the logical subject.', 'team_only', 'none'),
        ('dim_subject', 'last_loaded_at', 'internal', false, false, 'Selected current staging lineage timestamp for the logical subject.', 'team_only', 'none'),
        ('dim_recording', 'recording_sk', 'confidential', true, true, 'Pseudonymous Warehouse logical recording identity linked to a subject.', 'restricted', 'none'),
        ('dim_recording', 'recording_key', 'confidential', true, true, 'Pseudonymous logical recording/night identifier from a finite public health dataset.', 'restricted', 'none'),
        ('dim_recording', 'subject_sk', 'confidential', true, true, 'Pseudonymous Warehouse subject identity linked to the recording.', 'restricted', 'none'),
        ('dim_recording', 'source_system', 'internal', false, false, 'External source-system identifier.', 'team_only', 'none'),
        ('dim_recording', 'dataset_version', 'internal', false, false, 'Source dataset version.', 'team_only', 'none'),
        ('dim_recording', 'collection', 'confidential', false, true, 'Sleep-EDF study collection linked to a health-data recording.', 'restricted', 'none'),
        ('dim_recording', 'night_number', 'confidential', true, true, 'Subject recording-night number.', 'restricted', 'aggregate_only'),
        ('dim_recording', 'lights_off_seconds', 'confidential', true, true, 'Recording timing context that can contribute to re-identification.', 'restricted', 'aggregate_only'),
        ('dim_recording', 'treatment', 'confidential', true, true, 'Placebo or temazepam treatment context for Sleep Telemetry.', 'restricted', 'aggregate_only'),
        ('dim_recording', 'silver_recording_id', 'confidential', false, true, 'Concrete selected Silver health-data recording representation.', 'restricted', 'none'),
        ('dim_recording', 'recording_start', 'confidential', false, true, 'Recording start timestamp for patient-level sleep data.', 'restricted', 'none'),
        ('dim_recording', 'duration_seconds', 'confidential', false, true, 'Recording duration for patient-level sleep data.', 'restricted', 'none'),
        ('dim_recording', 'channel_count', 'confidential', false, true, 'Channel count for a patient-level sleep recording.', 'restricted', 'none'),
        ('dim_recording', 'annotation_count', 'confidential', false, true, 'Annotation count for a patient-level sleep recording.', 'restricted', 'none'),
        ('dim_recording', 'in_range_epoch_count', 'confidential', false, true, 'In-range epoch count for a patient-level sleep recording.', 'restricted', 'none'),
        ('dim_recording', 'out_of_range_epoch_count', 'confidential', false, true, 'Out-of-range annotation-derived epoch count for a patient-level sleep recording.', 'restricted', 'none'),
        ('dim_recording', 'trailing_overhang_seconds', 'confidential', false, true, 'Annotation overhang metadata for a patient-level sleep recording.', 'restricted', 'none'),
        ('dim_recording', 'psg_file_id', 'confidential', false, true, 'Bronze lineage pointer for the selected PSG recording.', 'restricted', 'none'),
        ('dim_recording', 'hypnogram_file_id', 'confidential', false, true, 'Bronze lineage pointer for the selected Hypnogram annotations.', 'restricted', 'none'),
        ('dim_recording', 'source_pair_id', 'confidential', false, true, 'Pseudonymous identity of one logical source recording pair.', 'restricted', 'none'),
        ('dim_recording', 'input_fingerprint', 'confidential', false, true, 'Content identity of one health-data source pair.', 'restricted', 'none'),
        ('dim_recording', 'config_id', 'internal', false, false, 'Silver transformation configuration identity.', 'team_only', 'none'),
        ('dim_recording', 'schema_version', 'internal', false, false, 'Silver schema version.', 'team_only', 'none'),
        ('dim_recording', 'transform_version', 'internal', false, false, 'Silver transformation version.', 'team_only', 'none'),
        ('dim_recording', 'psg_checksum_sha256', 'confidential', false, true, 'Verified checksum of the source PSG payload.', 'restricted', 'none'),
        ('dim_recording', 'hypnogram_checksum_sha256', 'confidential', false, true, 'Verified checksum of the source Hypnogram payload.', 'restricted', 'none'),
        ('dim_recording', 'silver_bucket', 'internal', false, false, 'Silver object-storage bucket.', 'team_only', 'none'),
        ('dim_recording', 'silver_output_prefix', 'confidential', false, true, 'Object prefix of the selected patient-level Silver representation.', 'restricted', 'none'),
        ('dim_recording', 'staging_load_run_id', 'internal', false, false, 'Operational lineage to the staging load run.', 'team_only', 'none'),
        ('dim_recording', 'first_loaded_at', 'internal', false, false, 'Earliest accepted staging lineage timestamp for the logical recording.', 'team_only', 'none'),
        ('dim_recording', 'last_loaded_at', 'internal', false, false, 'Latest selected staging lineage timestamp for the current logical recording row.', 'team_only', 'none'),
        ('dim_channel', 'recording_sk', 'confidential', true, true, 'Pseudonymous Warehouse recording identity linked to the channel.', 'restricted', 'none'),
        ('dim_channel', 'channel_sk', 'confidential', false, true, 'Warehouse channel identity inside a patient-level recording.', 'restricted', 'none'),
        ('dim_channel', 'silver_channel_id', 'confidential', false, true, 'Concrete Silver channel identity inside a patient-level recording.', 'restricted', 'none'),
        ('dim_channel', 'silver_recording_id', 'confidential', false, true, 'Concrete selected Silver recording identity.', 'restricted', 'none'),
        ('dim_channel', 'position', 'confidential', false, true, 'Channel position in a patient-level recording.', 'restricted', 'none'),
        ('dim_channel', 'source_label', 'confidential', false, true, 'Source channel label from a patient-level recording.', 'restricted', 'none'),
        ('dim_channel', 'normalized_name', 'confidential', false, true, 'Normalized channel name from a patient-level recording.', 'restricted', 'none'),
        ('dim_channel', 'sampling_frequency_hz', 'confidential', false, true, 'Sampling frequency of a patient-level signal channel.', 'restricted', 'none'),
        ('dim_channel', 'physical_dimension', 'confidential', false, true, 'Physical unit metadata for a patient-level signal channel.', 'restricted', 'none'),
        ('dim_channel', 'physical_min', 'confidential', false, true, 'Physical minimum metadata for a patient-level signal channel.', 'restricted', 'none'),
        ('dim_channel', 'physical_max', 'confidential', false, true, 'Physical maximum metadata for a patient-level signal channel.', 'restricted', 'none'),
        ('dim_channel', 'digital_min', 'confidential', false, true, 'Digital minimum metadata for a patient-level signal channel.', 'restricted', 'none'),
        ('dim_channel', 'digital_max', 'confidential', false, true, 'Digital maximum metadata for a patient-level signal channel.', 'restricted', 'none'),
        ('dim_channel', 'samples_per_data_record', 'confidential', false, true, 'Sampling-layout metadata for a patient-level signal channel.', 'restricted', 'none'),
        ('dim_channel', 'prefiltering', 'confidential', false, true, 'Prefiltering metadata for a patient-level signal channel.', 'restricted', 'none'),
        ('dim_channel', 'first_loaded_at', 'internal', false, false, 'Selected recording-representation staging timestamp used for channel lineage.', 'team_only', 'none'),
        ('dim_channel', 'last_loaded_at', 'internal', false, false, 'Selected recording-representation staging timestamp used for channel lineage.', 'team_only', 'none'),
        ('dim_sleep_stage', 'sleep_stage_sk', 'internal', false, false, 'Fixed controlled reference key for sleep-stage mapping.', 'team_only', 'none'),
        ('dim_sleep_stage', 'silver_stage_code', 'internal', false, false, 'Controlled source-preserving sleep-stage code.', 'team_only', 'none'),
        ('dim_sleep_stage', 'analytical_stage_code', 'internal', false, false, 'Controlled analytical sleep-stage grouping code.', 'team_only', 'none'),
        ('fact_sleep_epoch', 'sleep_epoch_sk', 'confidential', true, true, 'Pseudonymous Warehouse sleep-epoch identity linked to a recording and subject.', 'restricted', 'none'),
        ('fact_sleep_epoch', 'subject_sk', 'confidential', true, true, 'Pseudonymous Warehouse subject identity linked to epoch-level health data.', 'restricted', 'none'),
        ('fact_sleep_epoch', 'recording_sk', 'confidential', true, true, 'Pseudonymous Warehouse recording identity linked to epoch-level health data.', 'restricted', 'none'),
        ('fact_sleep_epoch', 'sleep_stage_sk', 'confidential', false, true, 'Sleep-stage classification for one patient-level epoch.', 'restricted', 'none'),
        ('fact_sleep_epoch', 'silver_epoch_id', 'confidential', false, true, 'Concrete Silver epoch identity for patient-level sleep data.', 'restricted', 'none'),
        ('fact_sleep_epoch', 'silver_recording_id', 'confidential', false, true, 'Concrete selected Silver recording identity.', 'restricted', 'none'),
        ('fact_sleep_epoch', 'source_interval_id', 'confidential', false, true, 'Source annotation-interval lineage for patient-level sleep data.', 'restricted', 'none'),
        ('fact_sleep_epoch', 'source_annotation_index', 'confidential', false, true, 'Source annotation index for patient-level sleep data.', 'restricted', 'none'),
        ('fact_sleep_epoch', 'epoch_number', 'confidential', false, true, 'Epoch position within a patient-level sleep recording.', 'restricted', 'none'),
        ('fact_sleep_epoch', 'start_seconds', 'confidential', false, true, 'Epoch start offset within a patient-level sleep recording.', 'restricted', 'none'),
        ('fact_sleep_epoch', 'duration_seconds', 'confidential', false, true, 'Epoch duration for patient-level sleep data.', 'restricted', 'none'),
        ('fact_sleep_epoch', 'end_seconds', 'confidential', false, true, 'Epoch end offset within a patient-level sleep recording.', 'restricted', 'none'),
        ('fact_sleep_epoch', 'source_label', 'confidential', false, true, 'Source annotation label for a patient-level sleep epoch.', 'restricted', 'none'),
        ('fact_sleep_epoch', 'silver_stage_code', 'confidential', false, true, 'Source-preserving normalized sleep-stage code for a patient-level epoch.', 'restricted', 'none'),
        ('fact_sleep_epoch', 'staging_load_run_id', 'internal', false, false, 'Operational lineage to the selected staging load run.', 'team_only', 'none'),
        ('fact_sleep_epoch', 'loaded_at', 'internal', false, false, 'Selected recording-representation staging load timestamp.', 'team_only', 'none')
) as warehouse_columns(
    table_name,
    column_name,
    classification_level,
    contains_personal_data,
    contains_health_data,
    sensitivity_reason,
    access_policy,
    masking_policy
)
on conflict (
    table_schema,
    table_name,
    column_name
)
do update set
    data_layer = excluded.data_layer,
    classification_level = excluded.classification_level,
    contains_personal_data = excluded.contains_personal_data,
    contains_health_data = excluded.contains_health_data,
    contains_direct_identifier = excluded.contains_direct_identifier,
    sensitivity_reason = excluded.sensitivity_reason,
    access_policy = excluded.access_policy,
    masking_policy = excluded.masking_policy,
    updated_at = now();
